[package]
name = "smcan"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-can = "0.4.1"

[dev-dependencies]
anyhow = "1.0.72"
socketcan = "2.0.0"
